export const signInTypes = {
  SET_FIRST_SIGNIN: 'SET_FIRST_SIGNIN',
  UPDATE_CONFIRMATION_PASSWORD: 'UPDATE_CONFIRMATION_PASSWORD',
  UPDATE_ERROR: 'UPDATE_ERROR',
  UPDATE_NEW_PASSWORD: 'UPDATE_NEW_PASSWORD',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_USERNAME: 'UPDATE_USERNAME',

}